name: "melos_monorepo"
publish_to: none

# This allows us to use melos on itself during development.
executables:
  melos: melos_dev

dev_dependencies:
  path: ^1.7.0
  yaml: ^3.1.0
  pubspec: ^2.0.0
  ansi_styles: ^0.3.0
  romantic_common: ^0.0.3
  logger:

# These allows us to use melos on itself during development.
# If you make a new local package in this repo that the melos package
# will depend on, then make sure to add it here otherwise you'll face
# "'pubspec.yaml' has been modified since".. issues.

environment:
  sdk: ">=2.2.2 <3.0.0"
