name: shellx_core
description: A Core tool for Command-line Shell with listening stdin
version: 0.0.1+1
repository: https://github.com/RomanticEra/shellx_core

environment:
  sdk: ">=2.14.0 <3.0.0"
dependencies:
  args: "^2.3.0"
  cli_util:
  colorize: "^3.0.0"
  universal_io: ^2.0.4

dev_dependencies:
  mocktail: ^0.2.0
  romantic_analysis: ^0.0.1-dev.1
  romantic_common:
    path: /Users/huangzheng/20211204/romantic/packages/romantic_common/
  test: ^1.19.2
executables:
  shellx_core:
scripts:
  test: |
    ## Run Dart tests and output them at directory `./coverage`:
    dart run test --coverage=./coverage

    ## Format collected coverage to LCOV (only for directory "lib")
    dart pub global run coverage:format_coverage --packages=.packages --report-on=lib --lcov -o ./coverage/lcov.info -i ./coverage --check-ignore
    derry get_coverage
  get_coverage: |
    ## Generate LCOV report:
    genhtml -o ./coverage/report ./coverage/lcov.info

    ## Open the HTML coverage report:
    open ./coverage/report/index.html
  commit: |
    dart run test
    readme_helper
    pana .
    git commit